AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AuditQueueArn:
    Type: String
  NotificationQueueArn:
    Type: String

  AuditLambdaRoleArn:
    Type: String

  NotificationLambdaRoleArn:
    Type: String

  DocumentTableName:
    Type: String

  FromEmail:
    Type: String  

Resources:

  AuditFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: audit-processor-lambda
      Runtime: python3.11
      CodeUri: event_processors/audit_processor/
      Handler: handler.lambda_handler
      Role: !Ref AuditLambdaRoleArn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DDB_TABLE_NAME: DocumentApproval
      Events:
        AuditQueueEvent:
          Type: SQS
          Properties:
            Queue: !Ref AuditQueueArn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notification-processor-lambda
      Runtime: python3.11
      CodeUri: event_processors/notification_processor/
      Handler: handler.lambda_handler
      Role: !Ref NotificationLambdaRoleArn
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: 1   
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
      Events:
        NotificationQueueEvent:
          Type: SQS
          Properties:
            Queue: !Ref NotificationQueueArn
            BatchSize: 1 
